# Generated by Django 5.0 on 2024-09-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=6)),
                ("model", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
