# Generated by Django 5.0 on 2024-09-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gorod",
            options={"verbose_name": "Города", "verbose_name_plural": "Города"},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Статус", "verbose_name_plural": "Статус"},
        ),
        migrations.AlterModelOptions(
            name="types",
            options={
                "verbose_name": "Модель автомобиля",
                "verbose_name_plural": "Модель автомобиля",
            },
        ),
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=6)),
                ("price", models.IntegerField()),
                ("cvet", models.CharField(max_length=150)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.types"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.status"
                    ),
                ),
                (
                    "town",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.gorod"
                    ),
                ),
            ],
        ),
    ]
